### ISSUE TITLE
Plugin triggers a fatal error when remediating

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/cgit-wp-remediator#1]
When attempting to remediate images, the following fatal error was encountered, ceasing execution of the Remediator:

`PHP Fatal error:  Call to private method Cgit\Remediator\Importer::import() from context 'Cgit\Remediator\Admin' in /path/to/site/public_html/wp-content/plugins/cgit-wp-remediator-master/classes/Cgit/Remediator/Admin.php on line 79
`

**Comment by johnkhughes** [comment]
Fixed in v1.1.2.
